import{S as m,i as a}from"./assets/vendor-46aac873.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerpolicy&&(t.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?t.credentials="include":e.crossorigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const f="https://pixabay.com/api/",c=new m(".js-gallery a.link-item",{navText:["←","→"],closeText:"×",enableKeyboard:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250}),s={formEl:document.querySelector('.js-search-form[data-id="1"]'),listEl:document.querySelector(".js-gallery"),inputEl:document.querySelector(".js-input"),loaderEl:document.querySelector(".js-loader")};s.formEl.addEventListener("submit",d);function d(r){r.preventDefault();const o=r.target.elements.query.value;s.loaderEl.style.display="block",E(),y(o).then(g).then(()=>{c.refresh(),c.on("error.simplelightbox",function(n){console.log(n)})}).catch(L).finally(()=>{s.loaderEl.style.display="none",p()})}function p(){s.inputEl.value=null}function y(r){const o={q:r,image_type:"photo",key:"42190247-000e45a6447d3626b5dd5a4c9",orientation:"horizontal",safesearch:!0},n=f+"?"+new URLSearchParams(o);return o.q===""?Promise.reject("Empty search query"):fetch(n).then(i=>i.json()).catch(i=>a.error({message:"Sorry, something is wrong! :)"}))}function g(r){if(r.hits.length===0)return a.error({message:"Sorry, there are no images matching your search query. Please try again!"});{const o=h(r.hits);s.listEl.innerHTML=o}}function h(r){return r.map(b).join("")}function b(r){const{largeImageURL:o,likes:n,views:i,webformatURL:e,tags:t,comments:l,downloads:u}=r;return`<li class="gallery-item">
    <a class="link-item" href="${o}"><img class="gallery-img" src="${e}" alt="${t}" title=""/></a>
      <div class="info">
        <p class="info-item"><b>Likes</b><br>${n}</p>
        <p class="info-item"><b>Views</b><br>${i}</p>
        <p class="info-item"><b>Comments</b><br>${l}</p>
        <p class="info-item"><b>Downloads</b><br>${u}</p>
      </div>
    </li>`}function E(){s.listEl.innerHTML=""}function L(r){console.error("Error:",r),a.error({message:"An error occurred. Please try again later."})}
//# sourceMappingURL=commonHelpers.js.map
