import{S as u,i as m}from"./assets/vendor-46aac873.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerpolicy&&(r.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?r.credentials="include":e.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const f="https://pixabay.com/api/",a=new u(".js-gallery a.link-item",{navText:["←","→"],closeText:"×",enableKeyboard:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250}),l={formEl:document.querySelector('.js-search-form[data-id="1"]'),listEl:document.querySelector(".js-gallery"),inputEl:document.querySelector(".js-input"),loaderEl:document.querySelector(".js-loader")};l.formEl.addEventListener("submit",d);function d(t){t.preventDefault();const o=t.target.elements.query.value;l.loaderEl.style.display="block",E(),y(o).then(g).then(()=>{a.refresh(),a.on("error.simplelightbox",function(n){console.log(n)})}).catch(L).finally(()=>{l.loaderEl.style.display="none",p()})}function p(){l.inputEl.value=null}function y(t){const o={q:t,image_type:"photo",key:"42190247-000e45a6447d3626b5dd5a4c9",orientation:"horizontal",safesearch:!0},n=f+"?"+new URLSearchParams(o);return o.q===""?Promise.reject("Empty search query"):fetch(n).then(i=>i.json())}function g(t){const o=b(t.hits);l.listEl.innerHTML=o}function b(t){return t.map(h).join("")}function h(t){const{largeImageURL:o,likes:n,views:i,webformatURL:e,tags:r,comments:s,downloads:c}=t;return`<li class="gallery-item">
    <a class="link-item" href="${o}"><img class="gallery-img" src="${e}" alt="${r}" title=""/></a>
      <div class="info">
        <p class="info-item"><b>Likes</b><br>${n}</p>
        <p class="info-item"><b>Views</b><br>${i}</p>
        <p class="info-item"><b>Comments</b><br>${s}</p>
        <p class="info-item"><b>Downloads</b><br>${c}</p>
      </div>
    </li>`}function E(){l.listEl.innerHTML=""}function L(t){console.error("Error:",t),m.error({message:"An error occurred. Please try again later."})}
//# sourceMappingURL=commonHelpers.js.map
